### ISSUE TITLE
error in "python setup.py install"

### ISSUE THREAD

**Issue by fbi0817** [idealwei/SuperPixelPool-pytorch#1]
Hi, Thanks for sharing your code. I have a problem when running:
python_ setup.py install

The error shows:

> suppixpool_cuda.cpp:38:44: error: could not convert ‘torch::CUDA((c10::ScalarType)3)’ from ‘at::TypeExtendedInterface’ to ‘c10::IntList {aka c10::ArrayRef<long int>}’
   at::Tensor output = at::zeros(torch::CUDA(at::kInt), {batch_size, channe
                                            ^
suppixpool_cuda.cpp:41:73: error: could not convert ‘c10::kInt’ from ‘const c10::ScalarType’ to ‘c10::IntList {aka c10::ArrayRef<long int>}’
  at::Tensor outIdx = -at::ones(at::kInt, {batch_size, channels_size, K});
                                                                        ^
error: command 'gcc' failed with exit status 1

I have upgraded my Pytorch from 0.4.0 to 1.0.0 and my gcc version is "gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609". But the error still appears. I am wondering whether it is due to the version of dependency? What ahout your settings? Thanks!

**Comment by idealwei** [comment]
I haven't met the error you referred. 

My environment settting :
gcc version： 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 
Pytorch version: 0.4.1

**Comment by idealwei** [comment]
You can try to  degrade your Pytorch version to 0.4.1
